name: ⚡️ Benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "master" # or "main"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: update pip
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel

      - name: get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|3.11|${{ hashFiles('setup.py') }}

      - run: pip install -e ".[test]"
      - uses: CodSpeedHQ/action@v2
        with:
          run: pytest . --codspeed
