name: 💅 Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< support-3.12
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
=======
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
>>>>>>> master
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run lint
      run: tox
      env:
        TOXENV: pre-commit
    - name: Run mypy
      run: tox
      env:
        TOXENV: mypy
